server:
  port: 8080

spring:
  profiles:
    active: "@activatedProperties@"
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

logging:
  config: classpath:log4j2.xml


name:
  domain: entity
  dao: dao
  mapper: mapper


parent:
  model: cn.com.funny.mall.base.BaseEntity
  dao: cn.com.funny.mall.base.BaseMapper

ignored:
  prefix: SYS,ERP,CRM,CC

sql:
  insert: insert
  update: updateById
  find: findById
  findList: findList
  count: count
  delete: deleteById